### ISSUE TITLE
Recipe in Data Project Fails to Validate

### ISSUE THREAD

**Issue by michael-tidd** [mapbox/real-time-maps#3]
When using the CLI validator the recipe.json file fails to validate.

`tilesets validate-recipe recipe.json`

{"valid": false, "errors": ["layers.county.features.id has an invalid expression.", "Bare objects invalid. Use [\"literal\", {...}] instead."]}

It appears the recipe spec may have changed since this project was published.

**Comment by michael-tidd** [comment]
#4

**Comment by michael-tidd** [comment]
I've submitted a pull request that now allows the recipe to pass validation: #4

**Comment by sansumbrella** [comment]
Fixed in #5 
Thanks!
