### ISSUE TITLE
Demo not working: API errors

### ISSUE THREAD

**Issue by raed667** [mapbox/real-time-maps#6]
Hello! 

When I tried the demo link: https://demos.mapbox.com/realtime-maps I get 2 API errors: 

1. https://d1fb3xy7os4v9k.cloudfront.net/election-stream Which just fails (503 Service Temporarily Unavailable)

2. https://api.mapbox.com/v4/mbxsolutions.conus-counties,mapbox.mapbox-streets-v8.json?secure&access_token=... which returns a 403 (maybe the key isn't good anymore?)

**Comment by cmtoomey** [comment]
@RaedsLab - thank you very much for the issue! I will get this addressed immediately.
